### ISSUE TITLE
Not enough arguments (missing: "group") on export

### ISSUE THREAD

**Issue by maj0rr** [vsch/laravel-translation-manager#74]
Hey @vsch ,

the import with modules works fine now. Editing entries also is fine. But when I try 
`php artisan translation:export`

I got the following exception:

```
[2017-03-07 20:12:23] local.ERROR: Symfony\Component\Console\Exception\RuntimeException: Not enough arguments (missing: "group"). in /var/www/vendor/symfony/console/Input/Input.php:84
Stack trace:
#0 /var/www/vendor/symfony/console/Command/Command.php(257): Symfony\Component\Console\Input\Input->validate()
#1 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#2 /var/www/vendor/symfony/console/Application.php(826): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Vsch\TranslationManager\Console\ExportCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(123): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 {main}  
```

I got the latest Laravel version 5.4.15

Any Idea with that?

**Comment by vsch** [comment]
@maj0rr, this is a command definition error. Add `"*"` for all groups or a specific group to export.

I will address the default for the command to be `"*"` all groups in the next release.

**Comment by vsch** [comment]
BTW, the help command lists the requirement of group

```
$ php artisan help translations:export
Usage:
  translations:export <group>

Arguments:
  group                 The group to export (`*` for all).

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --env[=ENV]       The environment the command should run under
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Export translations to PHP files

```

**Comment by maj0rr** [comment]
*DOH* :P 

Thanks!

**Comment by vsch** [comment]
@maj0rr, it seems to me to be more of a bug in command processing that fails to output the help string for the required argument instead of the generic error

![image](https://cloud.githubusercontent.com/assets/10299086/23677204/2d628390-034d-11e7-97e1-64c34687a65d.png)

**Comment by parse-code** [comment]
a tip:

you should do like 

`php artisan translations:export "*"`

but not 
`php artisan translations:export *`

It waste me  few minutes 😄
